version = 1

test_patterns = [
  "/resources/js/tests/**/*",
  "/tests/**/*"
]

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "mocha",
    "nodejs"
  ]
