version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "mocha",
    "nodejs"
  ]

test_patterns = [  
  "/resources/js/tests/store/modules/posts.spec.ts"
]
