version: '3.5'

services:
  php:
    environment:
      - PHP_IDE_CONFIG=serverName=coyote
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    command: postgres -c config_file=/etc/postgresql-prod.conf
    volumes:
      - ./docker/postgres/postgresql.local.conf:/etc/postgresql-prod.conf
    ports:
      - 5432:5432

  elasticsearch:
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  graylog:
    image: graylog/graylog:3.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:29000/
    networks:
      - coyote
    depends_on:
      - mongo
      - elasticsearch
    logging:
      options:
        max-size: 10m
    ports:
      - 29000:9000
      - 12201:12201
      - 12201:12201/udp

  mailhog:
    ports:
      - 8025:8025
